### ISSUE TITLE
Error suppression operator is not honoured

### ISSUE THREAD

**Issue by kAlvaro** [ScriptFUSION/PHPUnit-Immediate-Printer#17]
Our test suite is riddled with warnings since we use this extension. Most of them come from the Carbon library and they're clearly expected by authors:

![image](https://github.com/user-attachments/assets/14c05615-0cf0-464b-a798-700caae9ee61)

```php
$boundMacro = @$macro->bindTo($this, static::class) ?: @$macro->bindTo(null, static::class);
```

I've been doing some checks and it seems that the extension captures warnings but does not honour the `@` operator.

```php
<?php

namespace App\Tests\Application;

class ErrorSuppressionTest extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase
{
    public function testErrorSuppression(): void
    {
        $result = @$foo;
        $this->assertNull($result);
    }
}
```

```shell
./vendor/bin/phpunit -d display_errors=1 -d error_reporting=-1 --testsuite app tests/Application/ErrorSuppressionTest.php --testdox
```

![image](https://github.com/user-attachments/assets/240efd22-d9bc-4c8f-9168-a60ec8ae89a4)

If I disable the extension, nothing gets printed:

![image](https://github.com/user-attachments/assets/6d205c76-2281-441f-960d-a5d40add2bb1)

**Comment by Bilge** [comment]
Fixed in 🏷️ 3.5.0.

**Comment by kAlvaro** [comment]
The warning is no longer shown, but the test itself is still reported as "w". Is that expected?

```php
<?php

namespace App\Tests\Application;

class ErrorSuppressionTest extends \Symfony\Bundle\FrameworkBundle\Test\WebTestCase
{
    public function testErrorSuppression(): void
    {
        $result = @$foo;
        $this->assertNull($result);
    }

    public function testWarningsStillShown(): void
    {
        $result = $foo; // Line 15
        $this->assertNull($result);
    }
}
```

![image](https://github.com/user-attachments/assets/17998b42-093b-4450-b0e2-07a2344c0ed9)

**Comment by Bilge** [comment]
You are correct, the status should not be reported as `W` because this is inconsistent with the summary (Warnings: 1). Feel free to PR.

**Comment by kAlvaro** [comment]
@Bilge I've done some preliminary work at https://github.com/ScriptFUSION/Pip/pull/18
