### ISSUE TITLE
Doesn't support phpunit 7 (according to composer version requirements)

### ISSUE THREAD

**Issue by mfn** [ScriptFUSION/PHPUnit-Immediate-Printer#9]
Tried to install it:
```
 $ php composer.phar require --dev scriptfusion/phpunit-immediate-exception-printer
Using version ^2.0 for scriptfusion/phpunit-immediate-exception-printer
./composer.json has been updated
> php artisan clear-compiled
The compiled services & packages files have been removed.
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for scriptfusion/phpunit-immediate-exception-printer ^2.0 -> satisfiable by scriptfusion/phpunit-immediate-exception-printer[2.0.0].
    - scriptfusion/phpunit-immediate-exception-printer 2.0.0 requires phpunit/phpunit ^5.5|^6 -> satisfiable by phpunit/phpunit[5.5.0, 5.5.1, 5.5.2, 5.5.3, 5.5.4, 5.5.5, 5.5.6, 5.5.7, 5.5.x-dev, 5.6.0, 5.6.1, 5.6.2, 5.6.3, 5.6.4, 5.6.5, 5.6.6, 5.6.7, 5.6.8, 5.6.x-dev, 5.7.0, 5.7.1, 5.7.10, 5.7.11, 5.7.12, 5.7.13, 5.7.14, 5.7.15, 5.7.16, 5.7.17, 5.7.18, 5.7.19, 5.7.2, 5.7.20, 5.7.21, 5.7.22, 5.7.23, 5.7.24, 5.7.25, 5.7.26, 5.7.27, 5.7.3, 5.7.4, 5.7.5, 5.7.6, 5.7.7, 5.7.8, 5.7.9, 5.7.x-dev, 6.0.0, 6.0.1, 6.0.10, 6.0.11, 6.0.12, 6.0.13, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.0.8, 6.0.9, 6.0.x-dev, 6.1.0, 6.1.1, 6.1.2, 6.1.3, 6.1.4, 6.1.x-dev, 6.2.0, 6.2.1, 6.2.2, 6.2.3, 6.2.4, 6.2.x-dev, 6.3.0, 6.3.1, 6.3.x-dev, 6.4.0, 6.4.1, 6.4.2, 6.4.3, 6.4.4, 6.4.x-dev, 6.5.0, 6.5.1, 6.5.2, 6.5.3, 6.5.4, 6.5.5, 6.5.6, 6.5.x-dev] but these conflict with your requirements or minimum-stability.


Installation failed, reverting ./composer.json to its original content.
```
This is the phpunit version I've installed:
```
$ php composer.phar info phpunit/phpunit | grep versions
versions : * 7.0.1
```

**Comment by Bilge** [comment]
If there's no breaking changes in the printer functionality of v7, it should just be a case of relaxing the constraints. I suggest you try it and see by submitting a PR.

**Comment by funivan** [comment]
Create pr but Travis build failed. 

https://travis-ci.org/ScriptFUSION/PHPUnit-Immediate-Exception-Printer/jobs/388865414

**Comment by mfn** [comment]
Since the desire grew to have a working solution, I forked this package and made it (only) work with PHPUnit 8.5+ (and thus PHP 7.2+). Please see https://github.com/mfn/phpunit-immediate-exception-printer for anyone interested.

**Comment by Bilge** [comment]
If you add support for newer PHPUnit versions whilst maintaining backwards compatibility, I'll accept such a PR.

**Comment by mfn** [comment]
In my fork I removed all of that; it's a single non-multi-version file.

I also spent quite an mount of time fixing the tests (awesome idea how you did it, btw!) because some of _formatting_ output changed. I'm not sure I'm interested in trying to get this work with multiple PHPUnit version…

**Comment by Bilge** [comment]
Any clown can make a PHPUnit printer that supports just one version. If you want to contribute something of value to the open source community, grit your teeth on a real challenge and support all active versions.
